### ISSUE TITLE
Views are not rendering

### ISSUE THREAD

**Issue by edxco** [justalever/kickoff_tailwind#15]
Hi @justalever.

I tried to used your template but its not rendering. Im using 

> Rails 6.0.3.4
> ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-

- I cloned the repo and created the new app inside the the cloned repo's directory: `rails new sample_app -m template.rb`
- Moved to the sample_app directory and run `rails s`
- Open `http://localhost:3000/` on chrome or firefox 

The result is:

**On Google Chrome**
![Screenshot from 2020-11-24 19-00-07](https://user-images.githubusercontent.com/57426027/100168677-5404de80-2e87-11eb-8491-15d7289d07c1.png)

**On Firefox**
![Screenshot from 2020-11-24 19-00-49](https://user-images.githubusercontent.com/57426027/100168707-63842780-2e87-11eb-83a6-26bc08531e81.png)

Any advice is welcome

**Comment by justalever** [comment]
Give `bin/webpack` or `bin/webpack-dev-server` a try in another terminal window. 

I need to update this with the most recent tailwind release. On my to-do list!

**Comment by edxco** [comment]
Both options with errors:

```
warn - The `target` feature has been removed in Tailwind CSS v2.0.
warn - Please remove this option from your config file to silence this warning.
Hash: 93c190e08e54e282950f
Version: webpack 4.44.2
Time: 1155ms
```
Error on chrome or firefox:
```
Failed to compile.

./app/javascript/stylesheets/application.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/stylesheets/application.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

**Comment by justalever** [comment]
Yeah, my template is based on Tailwind pre 2.0.  In theory it still works but Tailwind 2.0 is using some bleeding edge tech (PostCSS 8). The webpack bundle in Rails hasn't caught up yet.

You could uninstall and reinstall a different version if Tailwind 1.9.6 I believe.

Or give this a shot 
https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

You'll need to swap the mentions of npm for yarn since that's what Rails ships with.

That ultimately might look like

```
yarn remove tailwindcss postcss autoprefixer 
yarn install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
```

My `tailwind.config.js` file needs an update as well. I think it's still safe to use but just wanted to give you a heads up.

**Comment by edxco** [comment]
Reinstalling Tailwind 1.9.6 works!
Thanks a lot for the help. I'm newbie on rails and Im following your videos to make an app, hopefully on time I will master rails.

**Comment by justalever** [comment]
I just added support for Tailwind 2.0! I'll close this 🤙
